name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y build-essential libssl-dev libtool libltdl-dev autoconf automake libcrack2-dev cracklib-runtime

      - name: Clone and build OpenLDAP
        run: |
          make openldap

      - name: Build module
        run: |
          make CRACKLIB=$PWD/tests/cracklib-dictionary/dict LOGGER_LEVEL=LOGGER_LEVEL_TRACE

      - name: Run integration tests
        run: |
          make test
